name: HTTP Server

on: [push, pull_request]

jobs:
  http_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Optional: If you need to handle YAML files

    - name: Start HTTP server
      run: |
        python -m http.server 8000 &  # Start HTTP server in background
        sleep 1  # Wait for server to start
        curl -sSf http://localhost:8000  # Test if server responds
